name: Fetch announcements from issue
on: issue_comment
jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Update Announcements
    if: |
      !github.event.issue.pull_request &&
      github.event.issue.number == 469 &&
      (github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'MEMBER' ||
      github.event.comment.author_association == 'CONTRIBUTOR' ||
      github.event.comment.author_association == 'COLLABORATOR')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/python_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r .github/python_requirements.txt
      - name: Run update_announcements script
        run: |
          python update_announcements.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Announcements"
          committer: "Hack Bot <uclaacmhack+ghbot@gmail.com>"
          author: "Hack Bot <uclaacmhack+ghbot@gmail.com>"
          branch: bot/updateAnnouncements
          title: '[Automated] Update announcement.json file'
          delete-branch: true
